### ISSUE TITLE
Add usage documentation.

### ISSUE THREAD

**Issue by josefnpat** [insweater/gamejoltlua#3]
It would be really nice if the lib was documented as a Lua module instead of having to reference the gamejolt http api.

I'd be willing to add this to the github wiki if you like!

**Comment by mbrovko** [comment]
I'm to start adding a few notes into wiki.

**Comment by mbrovko** [comment]
I guess I've got it. Anything more that I should add?

**Comment by pablomayobre** [comment]
There are many cases where you write for example `GJ.fetchThrophies(achieved)` while I guess `achieved` should be `"achieved"`. The same happens with `isGlobal` in the Data part. In other words, I would really like common use cases, with example values if possible

Other issue is the order of things, can I get all the throphies before I auth a user and start a session? Can I get global data without a session? The session I start uses the currently authenticated user? 
There is no order in the wiki, so I dont really know which thing is related to other part

Just a couple of suggestions, I hope it didnt sound aggressive or something like that. I really like your project!

**Comment by mbrovko** [comment]
_achieved_ and _isGlobal_ take boolean values. Got to add it to wiki, as well as a couple of other notes.

> Other issue is the order of things, can I get all the throphies before I auth a user and start a session? Can I get global data without a session?

No, you can't do that until you log in.
Though, session has no effect besides showing on GJ that user is currently playing your game.  

> The session I start uses the currently authenticated user?

Yes.

**Comment by mbrovko** [comment]
Hey @Positive07. What's the point of using GJ.setBigData?

**Comment by pablomayobre** [comment]
The same as setData but uses a POST request instead of a GET request, so you can send up t 16MB of data (You cant send that much with GET)

I decided to keep both because if you had to do an async version the big one should be async even to the asyncronous thread (a separate thread just for that request) while the other (setData) can run in the same thread maybe even in the main one.

SetData should be used for short data, like `true`, `15` and such, while setBigData should be used to save a huge map file or even an update for the game.

**Comment by mbrovko** [comment]
Oh, I see. Closing this issue then.
